In [1]:
import mysql.connector
import pandas as pd
from db_info import user,password,host,database,port

db_connection = mysql.connector.connect(
    host = host,
    user = user,
    password = password,
    database = database,
    port = port
)

cursor = db_connection.cursor()

cursor.execute("SELECT * FROM inheritance_list")

result = cursor.fetchall()

inheritance_list = pd.DataFrame(result, columns = [i[0] for i in cursor.description])

inheritance_list

,판례일련번호,사건명,사건번호,선고일자,법원명,사건종류명,판례상세링크
0,238913,예금[투자신탁 형태 단기금융집합투자기구(MMF) 수익권의 공동상속 효과가 문제된 사건],2023다221144,2023.12.21,대법원,민사,/DRF/lawService.do?OC=wanja1996&target=prec&ID...
1,240673,상속세부과처분취소,2021두52143,2023.12.21,대법원,일반행정,/DRF/lawService.do?OC=wanja1996&target=prec&ID...
2,237913,상속세부과처분취소[구 상증세법상 배우자 상속공제의 필수적 요건을 갖추었는지 여부가 ...,2023두44061,2023.11.02,대법원,세무,/DRF/lawService.do?OC=wanja1996&target=prec&ID...
3,237589,소유권이전등기[망인이 사망 전 유언하는 모습을 촬영한 망인의 차남인 원고가 사인증여...,2022다302237,2023.09.27,대법원,민사,/DRF/lawService.do?OC=wanja1996&target=prec&ID...
4,236923,상속세부과처분취소,2022누32308,2023.05.18,서울고등법원,세무,/DRF/lawService.do?OC=wanja1996&target=prec&ID...
...,...,...,...,...,...,...,...
4157,71780,지분권부존재확인청구사건,4287민공14,1954.05.13,광주고등법원,민사,/DRF/lawService.do?OC=wanja1996&target=prec&ID...
4158,86006,건물소유권이전등기청구,4287민상77,1954.03.31,대법원,민사,/DRF/lawService.do?OC=wanja1996&target=prec&ID...
4159,232305,행정처분취소청구사건,4287행3,1954.02.27,서울고등법원,일반행정,/DRF/lawService.do?OC=wanja1996&target=prec&ID...
4160,71777,토지인도청구사건,4286민공136,1953.10.09,광주고등법원,민사,/DRF/lawService.do?OC=wanja1996&target=prec&ID...
4161,85898,어업권공유확인,4285민상118,1952.02.12,대법원,민사,/DRF/lawService.do?OC=wanja1996&target=prec&ID...

In [2]:
inheritance_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4162 entries, 0 to 4161
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   판례일련번호  4162 non-null   int64
 1   사건명     4161 non-null   object
 2   사건번호    4162 non-null   object
 3   선고일자    4162 non-null   object
 4   법원명     4162 non-null   object
 5   사건종류명   4162 non-null   object
 6   판례상세링크  4162 non-null   object
dtypes: int64(1), object(6)
memory usage: 227.7+ KB

In [7]:
# '사건번호'가 4로 시작하지 않는 행만 필터링하여 새로운 데이터프레임 생성
filtered_df = inheritance_list[~inheritance_list['사건번호'].astype(str).str.startswith('4')][['판례일련번호', '사건번호', '선고일자']]

#4로 시작하는거
df_start4 = inheritance_list[inheritance_list['사건번호'].astype(str).str.startswith('4')][['판례일련번호', '사건번호', '선고일자']]

filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4119 entries, 0 to 4119
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   판례일련번호  4119 non-null   int64
 1   사건번호    4119 non-null   object
 2   선고일자    4119 non-null   object
dtypes: int64(1), object(2)
memory usage: 128.7+ KB

In [8]:
df_start4

      판례일련번호        사건번호        선고일자
4118  228205  4294민상1570  1962.06.21
4120  150518  4294민상1255  1962.05.17
4121  150533  4294민상1232  1962.05.10
4122  150536  4294민상1105  1962.05.03
4123  204184   4294민상676  1962.04.26
4124  150552  4294민상1159  1962.04.18
4125  232185  4293민공1983  1962.04.12
4126  150614   4294민상833  1962.03.22
4127  150647   4294민상168  1962.02.22
4128  150232   4294민상719  1962.01.25
4129  223861    4292민222  1961.11.30
4130   86552   4293민상116  1960.09.08
4131  228211   4292민상462  1960.07.07
4132   86523    4292민상55  1960.04.21
4133   86469   4292민상194  1959.11.05
4134   86463   4291민상709  1959.10.29
4135   71839   4292민공339  1959.09.25
4136   86417   4291민상221  1959.07.02
4137  209046   4291민상182  1959.04.30
4138   86337   4290민상308  1958.11.20
4139   71826   4291민공288  1958.10.22
4140   71820   4291민공120  1958.06.18
4141   71818    4290민공16  1958.02.26
4142  232281   4289민공230  1957.08.23
4143   86277    4290형상32  1957.04.12
4144   71804   4289민공292  1957.02.25
4145   86234   4288민상399  1956.12.22
4146  209001   4289민상319  1956.10.04
4147   86217   4289민상155  1956.05.17
4148  208937    4289민상59  1956.03.29
4149   86196   4288민상476  1956.03.22
4150  232297    4288민공84  1955.10.26
4151  208926    4288민상25  1955.09.15
4152  208993    4287행상84  1955.05.06
4153   86066    4288민상32  1955.04.14
4154   85952   4287민상238  1955.02.03
4155   85916    4286민상61  1954.12.23
4156   86063   4287민상366  1954.07.07
4157   71780    4287민공14  1954.05.13
4158   86006    4287민상77  1954.03.31
4159  232305      4287행3  1954.02.27
4160   71777   4286민공136  1953.10.09
4161   85898   4285민상118  1952.02.12

In [10]:
# 사건번호에서 '다' 앞의 숫자를 추출하여 '접수년도' 컬럼 추가
filtered_df['접수년도'] = filtered_df['사건번호'].str.extract(r'(\d+)')

# 결과 확인
print(filtered_df[['사건번호', '접수년도']])

             사건번호  접수년도
0     2023다221144  2023
1      2021두52143  2021
2      2023두44061  2023
3     2022다302237  2022
4      2022누32308  2022
...           ...   ...
4114       62다594    62
4115        62누29    62
4116       62다343    62
4117       62다272    62
4119       62다169    62

[4119 rows x 2 columns]

In [11]:
# 접수년도가 2글자인 경우 '19'를 붙여서 4글자로 변환
filtered_df['접수년도'] = filtered_df['접수년도'].apply(
    lambda x: '19' + x if len(x) == 2 else x
)


# 결과 확인
print(filtered_df[['사건번호', '접수년도']])

             사건번호  접수년도
0     2023다221144  2023
1      2021두52143  2021
2      2023두44061  2023
3     2022다302237  2022
4      2022누32308  2022
...           ...   ...
4114       62다594  1962
4115        62누29  1962
4116       62다343  1962
4117       62다272  1962
4119       62다169  1962

[4119 rows x 2 columns]

In [15]:
filtered_df['접수년도'].unique()

array(['2023', '2021', '2022', '2020', '2019', '2017', '2015', '2014',
       '2018', '2013', '2016', '2012', '2011', '2010', '2008', '2007',
       '2009', '2004', '2006', '2005', '2002', '2003', '2000', '2001',
       '1998', '1999', '1997', '1996', '1995', '1994', '1993', '1992',
       '1991', '1990', '1988', '1989', '1987', '1986', '1985', '1984',
       '1982', '1983', '1981', '1980', '1979', '1978', '1976', '1977',
       '1975', '1974', '1972', '1967', '1968', '1966', '2024', '1973',
       '1971', '1969', '1970', '1965', '1964', '1963', '1962'],
      dtype=object)

In [16]:
filtered_df.to_csv('inheritance_years.csv', index=False)